In [229]:
import numpy as np 
import pandas as pd
from sklearn.datasets import load_iris

In [230]:
data = load_iris()

In [231]:
X = data.data
y = data.target 

In [232]:
from sklearn.preprocessing import StandardScaler
import tensorflow 
from tensorflow import keras
from keras.utils import to_categorical

In [233]:
y_cat = to_categorical(y) 

In [234]:
from sklearn.model_selection import train_test_split

In [235]:
X_train, X_test, y_train, y_test = train_test_split(X, y_cat, test_size=0.2, random_state = 42)

In [236]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [237]:
from keras import Sequential
from keras.layers import Dense

In [238]:
model = Sequential()

model.add(Dense(16, activation = 'relu', input_shape = (4,)))
model.add(Dense(8, activation ='relu'))
model.add(Dense(3, activation = 'softmax'))

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [239]:
model.compile(optimizer = 'adam', loss = "categorical_crossentropy", metrics = ['accuracy'])

In [240]:
history = model.fit(X_train_sc, y_train,epochs = 50, batch_size=8, verbose = 1)

Epoch 1/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5529 - loss: 1.0268      
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6379 - loss: 0.9305
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6086 - loss: 0.8433
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6655 - loss: 0.7571
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6934 - loss: 0.6602
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6765 - loss: 0.6503
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7387 - loss: 0.6096
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7532 - loss: 0.5586
Epoch 9/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8566 - loss: 0.5091
Epoch 10/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.8606 - loss: 0.4723
Epoch 11/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8532 - loss: 0.4241
Epoch 12/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/

In [241]:
pred = model.predict(X_test_sc)

pred_labels = np.argmax(pred, axis = 1)
true_labels = np.argmax(y_test, axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step


In [242]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(true_labels,pred_labels)


acc

1.0

In [243]:
pred_labels

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [244]:
true_labels

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [245]:
X_test_sc.shape

(30, 4)

In [246]:
# # X_test এর 5 নম্বর data point
# sample = X_test[27]

# # Scale করতে হবে (কারণ model scaled ডেটা দিয়ে train হয়েছিল)
# sample_sc = sc.transform(sample.reshape(1, -1))

# # Predict
# sample_pred = model.predict(sample_sc)

# # Probability → class label
# sample_label = np.argmax(sample_pred, axis=1)

# sample, sample_label



In [247]:
sample = X_test[[26]]

sample_sc = sc.transform(sample)

sample_pred = model.predict(sample_sc)

sample_label = np.argmax(sample_pred, axis = 1)

sample, sample_pred, sample_label

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


(array([[6.7, 2.5, 5.8, 1.8]]),
 array([[3.5649369e-05, 4.5264173e-02, 9.5470023e-01]], dtype=float32),
 array([2]))